In [1]:
import numpy as np
arr=np.random.random((10,1))
print(arr)
m=np.mean(arr)
print(m)

[[0.31716223]
 [0.02532091]
 [0.92663127]
 [0.50068421]
 [0.76498283]
 [0.52082912]
 [0.14392986]
 [0.49431984]
 [0.98376012]
 [0.46281665]]
0.5140437032225164


In [2]:
import numpy as np
arr=np.random.random((20,1))
print(arr)
sd=np.std(arr)
print("Standard Deviation:", sd)
print("Variance:",sd*sd)

[[0.26499143]
 [0.71738448]
 [0.84242352]
 [0.5832938 ]
 [0.35669943]
 [0.69908167]
 [0.94470549]
 [0.42552214]
 [0.98640531]
 [0.1519505 ]
 [0.58885522]
 [0.09300807]
 [0.0725182 ]
 [0.49631011]
 [0.43484097]
 [0.90485682]
 [0.62196762]
 [0.17493776]
 [0.44681789]
 [0.62585752]]
Standard Deviation: 0.2740612048004195
Variance: 0.07510954397665749


In [3]:
import numpy as np
A=np.random.random((10,20))
B=np.random.random((20,25))
C=np.matmul(A,B)
print(C)
print("Sum of elements of C:",np.sum(C))

[[3.21457348 3.62568995 5.43114831 2.49377667 5.55923627 4.5334727
  4.17591595 4.43519789 4.78026703 4.06019017 3.27074853 4.36943267
  4.06129843 3.56845684 5.51593855 5.19428266 4.53414568 3.07442232
  4.60066815 4.77123399 4.61285539 3.86746354 4.04199811 3.5800458
  4.01247047]
 [4.17298217 4.44841869 5.371362   3.32523428 6.26518273 5.50557935
  4.32693331 5.07349109 4.30057376 4.59924472 3.35489967 4.62791621
  4.55876803 4.07672245 6.09806092 5.79560459 4.99607666 3.64321893
  5.72658123 5.1027267  4.7420201  4.9370046  4.84249651 3.59393591
  4.10701044]
 [5.35763068 4.82615115 6.23860402 3.27106206 6.23922696 6.04031005
  5.16373832 5.66844908 5.42215909 4.8677449  4.52103821 6.14685844
  5.01737413 4.47734655 5.91942628 6.08996828 5.80877955 4.80454641
  6.13474366 5.26143507 5.2907718  5.4211169  5.83079264 4.15655306
  5.12113368]
 [5.55190653 5.63771133 6.94383813 3.44779393 7.86312061 6.42377058
  5.87894707 6.3473629  6.50120388 5.59515273 4.51090031 6.24324839
  5.5664

In [6]:
import numpy as np
A=np.random.random((10,1))
print(A)
def func(y):
     return (1 / (1 + np.exp(-y)))

res = np.apply_along_axis(func, 0, A)

print('*'*50)

print(res)
    

[[0.32203904]
 [0.69180273]
 [0.10045117]
 [0.30824699]
 [0.1298569 ]
 [0.53568466]
 [0.49956313]
 [0.24403066]
 [0.67273481]
 [0.39727352]]
**************************************************
[[0.5798211 ]
 [0.66636783]
 [0.5250917 ]
 [0.57645731]
 [0.53241868]
 [0.63080799]
 [0.62235666]
 [0.5607067 ]
 [0.66211526]
 [0.59803242]]
